
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class UnitConfig : Luban.BeanBase
{
    public UnitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NickName = _buf.ReadString();
        ClassName = _buf.ReadString();
        MapNum = _buf.ReadInt();
        Position = _buf.ReadString();
        Angle = _buf.ReadString();
        Description = _buf.ReadString();
    }

    public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
    {
        return new UnitConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// NickName
    /// </summary>
    public readonly string NickName;
    /// <summary>
    /// ClassName
    /// </summary>
    public readonly string ClassName;
    /// <summary>
    /// MapNum
    /// </summary>
    public readonly int MapNum;
    /// <summary>
    /// Position
    /// </summary>
    public readonly string Position;
    /// <summary>
    /// Angle
    /// </summary>
    public readonly string Angle;
    /// <summary>
    /// #Description
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -568528378;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NickName:" + NickName + ","
        + "ClassName:" + ClassName + ","
        + "MapNum:" + MapNum + ","
        + "Position:" + Position + ","
        + "Angle:" + Angle + ","
        + "Description:" + Description + ","
        + "}";
    }
}

}

